export const INITIAL_ARTWORKS = [
  {
    title: "Ethereal Landscape",
    description: "An atmospheric oil painting capturing the morning mist over the Himalayan foothills.",
    price: 15000,
    category: "painting",
    artistName: "Aryan Sharma",
    medium: "Oil on Canvas",
    style: "Impressionism",
    dimensions: "24x36 inches",
    isHandmade: true,
    image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&q=80",
    artistId: "seed-user-1"
  },
  {
    title: "Obsidian Void",
    description: "A minimalist sculpture carved from a single block of black basalt, exploring negative space.",
    price: 45000,
    category: "sculpture",
    artistName: "Mira Patel",
    medium: "Basalt Stone",
    style: "Minimalism",
    dimensions: "12x12x18 inches",
    isHandmade: true,
    image: "https://images.unsplash.com/photo-1544216717-3bbf52512659?w=800&q=80",
    artistId: "seed-user-2"
  },
  {
    title: "Golden Hour Echo",
    description: "Fine art photography of a deserted palace at sunset, printed on archival metallic paper.",
    price: 8500,
    category: "photography",
    artistName: "Vikram Singh",
    medium: "Metallic Print",
    style: "Architectural",
    dimensions: "18x24 inches",
    isHandmade: false,
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&q=80",
    artistId: "seed-user-3"
  },
  {
    title: "Quantum Flux",
    description: "A generative digital masterpiece exploring the chaos and order of subatomic particles.",
    price: 12000,
    category: "digital",
    artistName: "Sneha Kapur",
    medium: "Generative Art",
    style: "Abstract",
    dimensions: "4K Resolution",
    isHandmade: false,
    image: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=800&q=80",
    artistId: "seed-user-4"
  },
  {
    title: "Hand-Dyed Indigo Silk",
    description: "A luxurious silk stole hand-dyed using traditional organic indigo fermentation processes.",
    price: 6200,
    category: "craft",
    artistName: "Sunita Raj",
    medium: "Pure Silk",
    style: "Traditional",
    dimensions: "2x7 feet",
    isHandmade: true,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80",
    artistId: "seed-user-5"
  },
  {
    title: "Megalithic Form",
    description: "Large scale bronze sculpture inspired by ancient tribal monoliths and mountain silhouettes.",
    price: 85000,
    category: "sculpture",
    artistName: "Arjun Mehta",
    medium: "Cast Bronze",
    style: "Modern",
    dimensions: "24x24x48 inches",
    isHandmade: true,
    image: "https://images.unsplash.com/photo-1600093463592-8e36ae95ef56?w=800&q=80",
    artistId: "seed-user-6"
  },
  {
    title: "Monsoon Over Varanasi",
    description: "Powerful watercolor capturing the intensity of a monsoon surge over the Ghats.",
    price: 21000,
    category: "painting",
    artistName: "Rohit Iyer",
    medium: "Watercolor on Paper",
    style: "Realism",
    dimensions: "30x40 inches",
    isHandmade: true,
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&q=80",
    artistId: "seed-user-7"
  },
  {
    title: "Street Souls #4",
    description: "Candid black and white street photography capturing a moment of laughter in a busy market.",
    price: 4800,
    category: "photography",
    artistName: "Dev Das",
    medium: "Giclee Print",
    style: "Documentary",
    dimensions: "12x18 inches",
    isHandmade: false,
    image: "https://images.unsplash.com/photo-1609766418204-94aae0ecfdfc?w=800&q=80",
    artistId: "seed-user-8"
  },
  {
    title: "Cybernetic Organism",
    description: "A surreal digital collage blending industrial machinery with natural biological forms.",
    price: 7500,
    category: "digital",
    artistName: "Zoya Ali",
    medium: "Digital Collage",
    style: "Surrealism",
    dimensions: "A2 Print",
    isHandmade: false,
    image: "https://images.unsplash.com/photo-1544216717-3bbf52512659?w=800&q=80",
    artistId: "seed-user-9"
  },
  {
    title: "Terracotta Guardian",
    description: "A hand-sculpted terracotta figure inspired by village deities of rural West Bengal.",
    price: 11500,
    category: "handmade",
    artistName: "Anjali Bose",
    medium: "Terracotta Clay",
    style: "Folk Art",
    dimensions: "10x10x20 inches",
    isHandmade: true,
    image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&q=80",
    artistId: "seed-user-10"
  },
  {
    title: "Macro Raindrops",
    description: "Breathtaking macro photography of morning dew on a lotus petal, printed on plexiglass.",
    price: 3200,
    category: "photography",
    artistName: "Kavita Rao",
    medium: "Plexiglass Print",
    style: "Nature",
    dimensions: "12x12 inches",
    isHandmade: false,
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca766d?w=800&q=80",
    artistId: "seed-user-11"
  },
  {
    title: "Woven Sea Kelp",
    description: "An intricate basket woven from dried sea kelp and sustainable seagrass fibers.",
    price: 5400,
    category: "craft",
    artistName: "Nandini Verma",
    medium: "Natural Fibers",
    style: "Environmental Art",
    dimensions: "15 inch diameter",
    isHandmade: true,
    image: "https://images.unsplash.com/photo-1558618047-3c8c76ca766d?w=800&q=80",
    artistId: "seed-user-12"
  },
  {
    title: "Abstract Fire Dance",
    description: "Vibrant acrylic piece with thick impasto strokes representing the energy of fire.",
    price: 18000,
    category: "painting",
    artistName: "Sanjay Gupta",
    medium: "Acrylic on Canvas",
    style: "Abstract Expressionism",
    dimensions: "30x30 inches",
    isHandmade: true,
    image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&q=80",
    artistId: "seed-user-13"
  },
  {
    title: "Liquid Mercury",
    description: "3D rendered digital art with fluid simulations and realistic metallic reflections.",
    price: 9900,
    category: "digital",
    artistName: "Rohan Khanna",
    medium: "3D Render",
    style: "Modern",
    dimensions: "UHD Digital File",
    isHandmade: false,
    image: "https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?w=800&q=80",
    artistId: "seed-user-14"
  },
  {
    title: "Hand-Carved Stone Totem",
    description: "A powerful stone pillar hand-carved with motifs from ancient maritime civilizations.",
    price: 32000,
    category: "handmade",
    artistName: "Ishaan Malhotra",
    medium: "Sandstone",
    style: "Ancient Modern",
    dimensions: "8x8x24 inches",
    isHandmade: true,
    image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=800&q=80",
    artistId: "seed-user-15"
  }
];
